name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Scripts
        run: |
          docker build -t app .
          docker login -u maksim343 -p dckr_pat_sk_vDKJ2QscHfPmqf_DsaRevSi4
          docker tag app maksim343/lab
          docker push maksim343/lab
    
